import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { client } from "../libs/client";
import { worksType } from "../types/worksType";

type Props = {
	works: Array<worksType>;
};

const Home: NextPage<Props> = (props) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Link href="/whenuseswr">useSWRでのフェッチ</Link>
				<p>制作一覧</p>
				{props.works.map((work) => (
					<div key={work.id}>
						<Link href={"/post/" + work.id} passHref>
							<h2>{work.name}</h2>
						</Link>
						<p>{work.desc}</p>
						<p>使用技術</p>
						{work.technologies.map((tech) => (
							<ul key={tech + work.id}>
								<li>{tech}</li>
							</ul>
						))}
					</div>
				))}
			</main>
		</div>
	);
};

export const getStaticProps = async () => {
	const data = await client.get({
		endpoint: "testworks",
	});

	return {
		props: {
			works: data.contents,
		},
	};
};

export default Home;
